project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
website:
  title: "Rory Lawless"
  site-url: https://rorylawless.com
  description: "Rory Lawless' personal website"
  repo-url: https://github.com/RoryLawless/rorylawless.com
  page-footer:
    background: "#fbf5f5"
    foreground: "#070a0c"
    center:
      - text: "Made by ðŸ‘½ in the District of Columbia"
  favicon: assets/favicon.svg
  search: false
  navbar:
    background: "#24617a"
    foreground: "#fbf5f5"
    right:
      - text: "{{< fa brands square-bluesky size=lg title='Bluesky' color='#fbf5f5'>}}"
        href: https://bsky.app/profile/rorylawless.com
        aria-label: "Bluesky"
      - text: "{{< fa brands git-alt size=lg title='GitHub' color='#fbf5f5'>}}"
        href: https://github.com/RoryLawless
        aria-label: "GitHub"
      - text: "{{< fa brands linkedin size=lg title='LinkedIn' color='#fbf5f5'>}}"
        href: https://www.linkedin.com/in/rory-lawless/
        aria-label: "LinkedIn"
format:
  html:
    theme:
      - none
      - assets/custom.scss
    highlight-style: a11y
    code-copy: true
    backgroundcolor: "#fbf5f5"
    mainfont: "Lato"
    fontcolor: "#070a0c"
    fontsize: 16pt
    linkcolor: "#183e4d"
execute:
  freeze: auto
